# generated by datamodel-codegen:
#   filename:  generation-1.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class SourceBase(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Annotated[str, Field(min_length=1)]
    type: str


class SourceGit(SourceBase):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['git']
    url: Annotated[str, Field(min_length=1)]
    ref: Annotated[str, Field(min_length=1)]
    clone_dir: Annotated[str, Field(alias='cloneDir')]
    """Relative path to directory of configuration file."""


class SourceLocal(SourceBase):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['local']
    path: Annotated[str, Field(min_length=1)]
    """Relative path to directory of configuration file."""


class SourceDocker(SourceBase):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['docker']
    image: Annotated[str, Field(min_length=1)]
    tag: Annotated[str, Field(min_length=1)]


class MainType(Enum):
    application = 'application'
    firmware = 'firmware'
    library = 'library'


class Options(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    path: Annotated[str, Field(min_length=1)]
    """The path of the 'package.json' manifest, relative to source (root) path."""
    lock_only: Annotated[bool, Field(alias='lockOnly')]
    """Use only the 'npm-shrinkwrap.json' or 'package-lock.json' lockfiles."""
    include_dev: Annotated[bool, Field(alias='includeDev')]
    include_optional: Annotated[bool, Field(alias='includeOptional')]
    include_peer: Annotated[bool, Field(alias='includePeer')]
    flatten: bool
    main_type: Annotated[MainType, Field(alias='mainType')]


class SpecVersion(str, Enum):
    field_1_0 = '1.0'
    field_1_1 = '1.1'
    field_1_2 = '1.2'
    field_1_3 = '1.3'
    field_1_4 = '1.4'
    field_1_5 = '1.5'
    field_1_6 = '1.6'
    field_1_7 = '1.7'


class GenerationOptionsBase1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    output_path: Annotated[str, Field(alias='outputPath', min_length=1)]
    """Absolute path or relative path to directory of configuration file."""
    format: Literal['xml']
    spec_version: Annotated[SpecVersion, Field(alias='specVersion')]


class SpecVersion1(str, Enum):
    field_1_2 = '1.2'
    field_1_3 = '1.3'
    field_1_4 = '1.4'
    field_1_5 = '1.5'
    field_1_6 = '1.6'
    field_1_7 = '1.7'


class GenerationOptionsBase2(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    output_path: Annotated[str, Field(alias='outputPath', min_length=1)]
    """Absolute path or relative path to directory of configuration file."""
    format: Literal['json']
    spec_version: Annotated[SpecVersion1, Field(alias='specVersion')]


class SpecVersion2(str, Enum):
    field_1_3 = '1.3'
    field_1_4 = '1.4'
    field_1_5 = '1.5'
    field_1_6 = '1.6'
    field_1_7 = '1.7'


class GenerationOptionsBase3(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    output_path: Annotated[str, Field(alias='outputPath', min_length=1)]
    """Absolute path or relative path to directory of configuration file."""
    format: Literal['proto']
    spec_version: Annotated[SpecVersion2, Field(alias='specVersion')]


class GenerationOptionsNPM1(GenerationOptionsBase1):
    pass


class GenerationOptionsNPM2(GenerationOptionsBase2):
    pass


class GenerationOptionsNPM3(GenerationOptionsBase3):
    pass


class Format(str, Enum):
    json = 'json'
    xml = 'xml'


class SpecVersion6(str, Enum):
    field_1_2 = '1.2'
    field_1_3 = '1.3'
    field_1_4 = '1.4'
    field_1_5 = '1.5'
    field_1_6 = '1.6'


class GenerationOptionsNPM4(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    format: Format
    spec_version: Annotated[SpecVersion6, Field(alias='specVersion')]


class GenerationOptionsNPM5(GenerationOptionsNPM1, GenerationOptionsNPM4):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class GenerationOptionsNPM6(GenerationOptionsNPM2, GenerationOptionsNPM4):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class GenerationOptionsNPM7(GenerationOptionsNPM3, GenerationOptionsNPM4):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class OptionsNPM(Options):
    pass


class TargetBase(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Annotated[str, Field(min_length=1)]
    type: str
    source_id: Annotated[str, Field(alias='sourceId', min_length=1)]
    enabled: bool = True
    options: dict[str, object] | None = None
    generation: GenerationOptionsBase1 | GenerationOptionsBase2 | GenerationOptionsBase3


class TargetNPM(TargetBase):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['npm']
    generation: GenerationOptionsNPM5 | GenerationOptionsNPM6 | GenerationOptionsNPM7
    options: Options


class TargetDocker(TargetBase):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['docker']


class SBOMGenerationConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    version: Literal[1]
    sources: Annotated[
        list[SourceGit | SourceLocal | SourceDocker], Field(min_length=1)
    ]
    targets: Annotated[list[TargetNPM | TargetDocker], Field(min_length=1)]
