version: 2

updates:
  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      devcontainers-dependencies:
        patterns:
          - "*"
  
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/src/sbom_generator/deps/npm"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      cyclonedx-npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/src/sbom_generator/deps/yarn"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      cyclonedx-yarn-dependencies:
        patterns:
          - "*"

  - package-ecosystem: bundler
    directory: "/src/sbom_generator/deps/ruby"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      cyclonedx-ruby-dependencies:
        patterns:
          - "*"