version: 1

sources:
  - id: pangolin
    type: git
    url: "https://github.com/fosrl/pangolin.git"
    ref: "1.19.4"
    cloneDir: "../repos/pangolin"

targets:
  - id: "server"
    type: npm
    sourceId: "pangolin"
    generation:
      outputPath: "../sboms/server.cdx.json"
      format: json
      specVersion: "1.6"
    options:
      includeDev: false
      includeOptional: true
      includePeer: true
      flatten: false
      path: "./package.json"
      lockOnly: true
      mainType: application

  - id: "server-lock"
    type: npm
    sourceId: "pangolin"
    generation:
      outputPath: "../sboms/server-lock.cdx.json"
      format: json
      specVersion: "1.6"
    options:
      includeDev: false
      includeOptional: true
      includePeer: true
      flatten: false
      path: "./package.json"
      lockOnly: true
      mainType: application
